// Compatibility wrapper over the local generated Thaqalayn dataset.
// Runtime data lives under /public/data/thaqalayn/current and is generated by scripts/data.

import { matchesSearchMode } from './search-utils'
import { idbGetData, idbSetData } from './hadith-cache'

const jsonCache = new Map<string, Promise<unknown>>()
let runtimeBasePromise: Promise<string> | null = null

// Runtime artifacts are content-addressed by dataset version (the URL carries
// the version), so a body cached for a given URL never goes stale. The TTL only
// bounds how long an entry survives in IndexedDB before it is re-fetched.
const RUNTIME_CACHE_TTL = 30 * 24 * 60 * 60 * 1000 // 30 days

function withBasePath(path: string) {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH || ''
  return `${basePath}${path}`
}

async function getRuntimeBase(): Promise<string> {
  if (runtimeBasePromise) return runtimeBasePromise

  runtimeBasePromise = (async () => {
    try {
      const response = await fetch(withBasePath('/data/thaqalayn/current/manifest.json'), {
        headers: { Accept: 'application/json' },
      })
      if (!response.ok) return '/data/thaqalayn/current/runtime'
      const manifest = (await response.json()) as { version?: string }
      return manifest.version
        ? `/data/thaqalayn/${manifest.version}/runtime`
        : '/data/thaqalayn/current/runtime'
    } catch {
      return '/data/thaqalayn/current/runtime'
    }
  })()

  return runtimeBasePromise
}

async function loadRuntimeJson<T>(url: string): Promise<T> {
  // Durable cache first: a volume fetched in any prior session or tab is served
  // from IndexedDB with no network request and no JSON re-parse from text.
  try {
    const persisted = await idbGetData(url)
    if (persisted != null) return persisted as T
  } catch {
    // Ignore cache-read failures and fall through to the network.
  }

  const response = await fetch(url, { headers: { Accept: 'application/json' } })
  if (!response.ok) throw new Error(`Local data error: ${response.status} ${response.statusText}`)
  const data = (await response.json()) as T
  // Persist in the background; best-effort, never blocks the returned value.
  void idbSetData(url, data, RUNTIME_CACHE_TTL)
  return data
}

async function fetchRuntimeJson<T>(path: string): Promise<T> {
  const runtimeBase = await getRuntimeBase()
  const url = withBasePath(`${runtimeBase}${path}`)
  const cached = jsonCache.get(url)
  if (cached) return cached as Promise<T>

  const promise = loadRuntimeJson<T>(url)
  // Drop a rejected promise so a later call can retry instead of being stuck
  // resolving to the same failure for the rest of the session.
  promise.catch(() => {
    if (jsonCache.get(url) === promise) jsonCache.delete(url)
  })
  jsonCache.set(url, promise)
  return promise
}

// Lazily-built map of bookId → hadith id range, read from books.json. Used to
// pick the right volume for an ambiguous multi-volume hadith id without
// downloading every volume. Cached for the session.
let bookIdRangesPromise: Promise<Record<string, { min: number; max: number }>> | null = null
async function getBookIdRanges(): Promise<Record<string, { min: number; max: number }>> {
  if (!bookIdRangesPromise) {
    bookIdRangesPromise = fetchRuntimeJson<BookInfo[]>('/books.json')
      .then((books) => {
        const ranges: Record<string, { min: number; max: number }> = {}
        for (const book of books) {
          ranges[book.bookId] = { min: book.idRangeMin, max: book.idRangeMax }
        }
        return ranges
      })
      .catch(() => ({}))
  }
  return bookIdRangesPromise
}

// Types for API-compatible responses
export interface HadithGrading {
  grade_en: string | null
  grade_ar: string | null
  reference_en: string
  author: {
    name_en: string
    name_ar: string | null
    link: string | null
    death_date: string | null
  }
}

export interface Hadith {
  _id: string
  id: number
  bookId: string
  book: string
  category: string
  categoryId: string
  chapter: string
  author: string
  translator: string
  englishText: string
  arabicText: string
  majlisiGrading: string
  URL: string
  volume: number
  frenchText: string
  mohseniGrading: string
  behbudiGrading: string
  chapterInCategoryId: number
  thaqalaynSanad: string
  thaqalaynMatn: string
  gradingsFull: HadithGrading[]
  __v: number
}

export interface BookInfo {
  bookId: string
  BookName: string
  author: string
  idRangeMin: number
  idRangeMax: number
  bookDescription: string
  bookCover: string
  englishName: string
  translator: string
  volume: number
}

export interface QueryResponse {
  results: Hadith[]
  total: number
}

export interface ChapterInfo {
  chapter: string
  chapterInCategoryId: number
  hadiths: Hadith[]
}

export interface CategoryInfo {
  category: string
  categoryId: string
  chapters: Record<string, ChapterInfo>
}

export interface ChapterStructure {
  [categoryKey: string]: CategoryInfo
}

function searchHadiths(hadiths: Hadith[], query: string): Hadith[] {
  const trimmed = query.trim()
  if (!trimmed) return hadiths

  return hadiths.filter((hadith) =>
    matchesSearchMode({
      query: trimmed,
      mode: 'exactPhrase',
      englishText: hadith.englishText || hadith.thaqalaynMatn,
      arabicText: hadith.arabicText || hadith.thaqalaynMatn,
    }),
  )
}

function getRandomFromList<T>(items: T[]): T {
  if (items.length === 0) throw new Error('Cannot choose a random item from an empty list')
  return items[Math.floor(Math.random() * items.length)]
}

/**
 * Fetch a random hadith from the tiny server endpoint (backed by the
 * dataset's purpose-built random.json refs) instead of downloading a whole
 * multi-MB volume client-side just to pick one entry.
 */
export async function fetchRandomHadith(bookId?: string): Promise<Hadith> {
  const params = bookId ? `?book=${encodeURIComponent(bookId)}` : ''
  const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/api/random${params}`, {
    headers: { Accept: 'application/json' },
  })
  const data = await response.json()
  if (!response.ok || data?.error) throw new Error(data?.error || 'Random hadith failed')
  return data as Hadith
}

export const thaqalaynApi = {
  async getAllBooks(): Promise<BookInfo[]> {
    return fetchRuntimeJson<BookInfo[]>('/books.json')
  },

  async getRandomHadithFromBook(bookId: string): Promise<Hadith> {
    const hadiths = await this.getBookHadiths(bookId)
    return getRandomFromList(hadiths)
  },

  async searchBook(bookId: string, query: string): Promise<QueryResponse> {
    const hadiths = await this.getBookHadiths(bookId)
    const results = searchHadiths(hadiths, query)
    return { results, total: results.length }
  },

  async getBookHadiths(bookId: string): Promise<Hadith[]> {
    return fetchRuntimeJson<Hadith[]>(`/volumes/${encodeURIComponent(bookId)}.json`)
  },

  /**
   * Warm the cache for a volume in the background (e.g. on navigation intent).
   * Idempotent — repeat calls are deduped by getBookHadiths' caches — and never
   * throws, so callers can fire-and-forget.
   */
  prefetchVolume(bookId: string): void {
    if (!bookId) return
    void this.getBookHadiths(bookId).catch(() => {})
  },

  async getSpecificHadith(bookId: string, hadithId: number): Promise<Hadith> {
    const hadiths = await this.getBookHadiths(bookId)
    const found = hadiths.find((hadith) => hadith.id === hadithId)
    if (!found) throw new Error(`No hadith ${hadithId} in ${bookId}`)
    return found
  },

  async findHadithAcrossBooks(bookIds: string[], hadithId: number): Promise<Hadith | null> {
    // Hadith ids restart at 1 in every volume, so a multi-volume id is ambiguous
    // and the established contract is "the lowest-numbered volume containing this
    // id wins". We preserve that exactly, but rather than downloading every
    // volume in parallel (≈50 MB across all 8 Al-Kāfi volumes just to show one
    // hadith) we use each volume's id range to try the likely volume(s) first and
    // fetch sequentially, stopping at the first match — normally a single volume.
    const ranges = await getBookIdRanges()
    const inRange = (bookId: string) => {
      const range = ranges[bookId]
      // Unknown range → keep it a candidate so a hadith is never missed.
      return !range || (hadithId >= range.min && hadithId <= range.max)
    }

    // In-range volumes first (original order preserved so the lowest matching
    // volume still wins), then the rest as a safety net for gaps/missing ranges.
    const primary = bookIds.filter(inRange)
    const fallback = bookIds.filter((bookId) => !primary.includes(bookId))

    for (const bookId of [...primary, ...fallback]) {
      try {
        const hadiths = await this.getBookHadiths(bookId)
        const found = hadiths.find((hadith) => hadith.id === hadithId)
        if (found) return found
      } catch {
        // Ignore a missing/failed volume and continue with the next candidate.
      }
    }

    return null
  },
}

export const alKafiApi = {
  getAlKafiVolumes(): string[] {
    return [
      'Al-Kafi-Volume-1-Kulayni',
      'Al-Kafi-Volume-2-Kulayni',
      'Al-Kafi-Volume-3-Kulayni',
      'Al-Kafi-Volume-4-Kulayni',
      'Al-Kafi-Volume-5-Kulayni',
      'Al-Kafi-Volume-6-Kulayni',
      'Al-Kafi-Volume-7-Kulayni',
      'Al-Kafi-Volume-8-Kulayni',
    ]
  },

  async getRandomHadithFromVolume(volume: number): Promise<Hadith> {
    if (volume < 1 || volume > 8) throw new Error('Al-Kafi volume must be between 1 and 8')
    return thaqalaynApi.getRandomHadithFromBook(`Al-Kafi-Volume-${volume}-Kulayni`)
  },

  async getVolumeHadiths(volume: number): Promise<Hadith[]> {
    if (volume < 1 || volume > 8) throw new Error('Al-Kafi volume must be between 1 and 8')
    return thaqalaynApi.getBookHadiths(`Al-Kafi-Volume-${volume}-Kulayni`)
  },

  async getVolumeChapterStructure(volume: number): Promise<ChapterStructure> {
    const hadiths = await this.getVolumeHadiths(volume)
    return buildChapterStructure(hadiths)
  },

  async getChapterHadiths(
    volume: number,
    categoryId: string,
    chapterId: number,
  ): Promise<Hadith[]> {
    const allHadiths = await this.getVolumeHadiths(volume)
    return allHadiths.filter(
      (hadith) => hadith.categoryId === categoryId && hadith.chapterInCategoryId === chapterId,
    )
  },
}

export const uyunApi = {
  getUyunVolumes(): string[] {
    return ['Uyun-akhbar-al-Rida-Volume-1-Saduq', 'Uyun-akhbar-al-Rida-Volume-2-Saduq']
  },

  async getVolumeHadiths(volume: number): Promise<Hadith[]> {
    if (volume < 1 || volume > 2) {
      throw new Error('Uyun akhbar al-Rida volume must be between 1 and 2')
    }
    return thaqalaynApi.getBookHadiths(`Uyun-akhbar-al-Rida-Volume-${volume}-Saduq`)
  },

  async getVolumeChapterStructure(volume: number): Promise<ChapterStructure> {
    const hadiths = await this.getVolumeHadiths(volume)
    return buildChapterStructure(hadiths)
  },

  async getChapterHadiths(
    volume: number,
    categoryId: string,
    chapterId: number,
  ): Promise<Hadith[]> {
    const allHadiths = await this.getVolumeHadiths(volume)
    return allHadiths.filter(
      (hadith) => hadith.categoryId === categoryId && hadith.chapterInCategoryId === chapterId,
    )
  },
}

export const bookApi = {
  async getBookHadiths(bookId: string): Promise<Hadith[]> {
    return thaqalaynApi.getBookHadiths(bookId)
  },

  async getBookChapterStructure(bookId: string): Promise<ChapterStructure> {
    const hadiths = await this.getBookHadiths(bookId)
    return buildChapterStructure(hadiths)
  },

  async getChapterHadiths(
    bookId: string,
    categoryId: string,
    chapterInCategoryId: number,
  ): Promise<Hadith[]> {
    const allHadiths = await this.getBookHadiths(bookId)
    return allHadiths.filter(
      (hadith) =>
        hadith.categoryId === categoryId && hadith.chapterInCategoryId === chapterInCategoryId,
    )
  },
}

function buildChapterStructure(hadiths: Hadith[]): ChapterStructure {
  const structure: ChapterStructure = {}

  for (const hadith of hadiths) {
    const categoryKey = hadith.category || 'Uncategorized'
    const chapterKey = hadith.chapter || 'No Chapter'

    structure[categoryKey] ??= {
      category: categoryKey,
      categoryId: hadith.categoryId || '',
      chapters: {},
    }

    structure[categoryKey].chapters[chapterKey] ??= {
      chapter: chapterKey,
      chapterInCategoryId: hadith.chapterInCategoryId || 0,
      hadiths: [],
    }

    structure[categoryKey].chapters[chapterKey].hadiths.push(hadith)
  }

  for (const category of Object.values(structure)) {
    category.chapters = Object.fromEntries(
      Object.entries(category.chapters).sort(
        ([, a], [, b]) => a.chapterInCategoryId - b.chapterInCategoryId,
      ),
    )
  }

  return structure
}
