// Compatibility wrapper over the local generated Thaqalayn dataset.
// Runtime data lives under /public/data/thaqalayn/current and is generated by scripts/data.

import { matchesSearchMode } from './search-utils'

const jsonCache = new Map<string, Promise<unknown>>()
let runtimeBasePromise: Promise<string> | null = null

function withBasePath(path: string) {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH || ''
  return `${basePath}${path}`
}

async function getRuntimeBase(): Promise<string> {
  if (runtimeBasePromise) return runtimeBasePromise

  runtimeBasePromise = (async () => {
    try {
      const response = await fetch(withBasePath('/data/thaqalayn/current/manifest.json'), {
        headers: { Accept: 'application/json' },
      })
      if (!response.ok) return '/data/thaqalayn/current/runtime'
      const manifest = (await response.json()) as { version?: string }
      return manifest.version
        ? `/data/thaqalayn/${manifest.version}/runtime`
        : '/data/thaqalayn/current/runtime'
    } catch {
      return '/data/thaqalayn/current/runtime'
    }
  })()

  return runtimeBasePromise
}

async function fetchRuntimeJson<T>(path: string): Promise<T> {
  const runtimeBase = await getRuntimeBase()
  const url = withBasePath(`${runtimeBase}${path}`)
  const cached = jsonCache.get(url)
  if (cached) return cached as Promise<T>

  const promise = fetch(url, { headers: { Accept: 'application/json' } }).then(async (response) => {
    if (!response.ok) throw new Error(`Local data error: ${response.status} ${response.statusText}`)
    return (await response.json()) as T
  })

  jsonCache.set(url, promise)
  return promise
}

// Types for API-compatible responses
export interface HadithGrading {
  grade_en: string | null
  grade_ar: string | null
  reference_en: string
  author: {
    name_en: string
    name_ar: string | null
    link: string | null
    death_date: string | null
  }
}

export interface Hadith {
  _id: string
  id: number
  bookId: string
  book: string
  category: string
  categoryId: string
  chapter: string
  author: string
  translator: string
  englishText: string
  arabicText: string
  majlisiGrading: string
  URL: string
  volume: number
  frenchText: string
  mohseniGrading: string
  behbudiGrading: string
  chapterInCategoryId: number
  thaqalaynSanad: string
  thaqalaynMatn: string
  gradingsFull: HadithGrading[]
  __v: number
}

export interface BookInfo {
  bookId: string
  BookName: string
  author: string
  idRangeMin: number
  idRangeMax: number
  bookDescription: string
  bookCover: string
  englishName: string
  translator: string
  volume: number
}

export interface QueryResponse {
  results: Hadith[]
  total: number
}

export interface ChapterInfo {
  chapter: string
  chapterInCategoryId: number
  hadiths: Hadith[]
}

export interface CategoryInfo {
  category: string
  categoryId: string
  chapters: Record<string, ChapterInfo>
}

export interface ChapterStructure {
  [categoryKey: string]: CategoryInfo
}

async function getAllBookIds() {
  const books = await thaqalaynApi.getAllBooks()
  return books.map((book) => book.bookId)
}

function searchHadiths(hadiths: Hadith[], query: string): Hadith[] {
  const trimmed = query.trim()
  if (!trimmed) return hadiths

  return hadiths.filter((hadith) =>
    matchesSearchMode({
      query: trimmed,
      mode: 'exactPhrase',
      englishText: hadith.englishText || hadith.thaqalaynMatn,
      arabicText: hadith.arabicText || hadith.thaqalaynMatn,
    }),
  )
}

function getRandomFromList<T>(items: T[]): T {
  if (items.length === 0) throw new Error('Cannot choose a random item from an empty list')
  return items[Math.floor(Math.random() * items.length)]
}

export const thaqalaynApi = {
  async getAllBooks(): Promise<BookInfo[]> {
    return fetchRuntimeJson<BookInfo[]>('/books.json')
  },

  async getRandomHadith(): Promise<Hadith> {
    const bookIds = await getAllBookIds()
    return this.getRandomHadithFromBook(getRandomFromList(bookIds))
  },

  async getRandomHadithFromBook(bookId: string): Promise<Hadith> {
    const hadiths = await this.getBookHadiths(bookId)
    return getRandomFromList(hadiths)
  },

  async searchAllBooks(query: string): Promise<QueryResponse> {
    const bookIds = await getAllBookIds()
    const resultsByBook = await Promise.all(bookIds.map((bookId) => this.searchBook(bookId, query)))
    const results = resultsByBook.flatMap((response) => response.results)
    return { results, total: results.length }
  },

  async searchBook(bookId: string, query: string): Promise<QueryResponse> {
    const hadiths = await this.getBookHadiths(bookId)
    const results = searchHadiths(hadiths, query)
    return { results, total: results.length }
  },

  async getBookHadiths(bookId: string): Promise<Hadith[]> {
    return fetchRuntimeJson<Hadith[]>(`/volumes/${encodeURIComponent(bookId)}.json`)
  },

  async getSpecificHadith(bookId: string, hadithId: number): Promise<Hadith> {
    const hadiths = await this.getBookHadiths(bookId)
    const found = hadiths.find((hadith) => hadith.id === hadithId)
    if (!found) throw new Error(`No hadith ${hadithId} in ${bookId}`)
    return found
  },

  async findHadithAcrossBooks(bookIds: string[], hadithId: number): Promise<Hadith | null> {
    const results = await Promise.allSettled(
      bookIds.map((bookId) => this.getSpecificHadith(bookId, hadithId)),
    )

    for (const result of results) {
      if (result.status === 'fulfilled') return result.value
    }

    return null
  },
}

export const alKafiApi = {
  getAlKafiVolumes(): string[] {
    return [
      'Al-Kafi-Volume-1-Kulayni',
      'Al-Kafi-Volume-2-Kulayni',
      'Al-Kafi-Volume-3-Kulayni',
      'Al-Kafi-Volume-4-Kulayni',
      'Al-Kafi-Volume-5-Kulayni',
      'Al-Kafi-Volume-6-Kulayni',
      'Al-Kafi-Volume-7-Kulayni',
      'Al-Kafi-Volume-8-Kulayni',
    ]
  },

  async getRandomAlKafiHadith(): Promise<Hadith> {
    return thaqalaynApi.getRandomHadithFromBook(getRandomFromList(this.getAlKafiVolumes()))
  },

  async getRandomHadithFromVolume(volume: number): Promise<Hadith> {
    if (volume < 1 || volume > 8) throw new Error('Al-Kafi volume must be between 1 and 8')
    return thaqalaynApi.getRandomHadithFromBook(`Al-Kafi-Volume-${volume}-Kulayni`)
  },

  async searchAlKafi(query: string): Promise<QueryResponse> {
    const responses = await Promise.all(
      this.getAlKafiVolumes().map((id) => thaqalaynApi.searchBook(id, query)),
    )
    const results = responses.flatMap((response) => response.results)
    return { results, total: results.length }
  },

  async getVolumeHadiths(volume: number): Promise<Hadith[]> {
    if (volume < 1 || volume > 8) throw new Error('Al-Kafi volume must be between 1 and 8')
    return thaqalaynApi.getBookHadiths(`Al-Kafi-Volume-${volume}-Kulayni`)
  },

  async getVolumeChapterStructure(volume: number): Promise<ChapterStructure> {
    const hadiths = await this.getVolumeHadiths(volume)
    return buildChapterStructure(hadiths)
  },

  async getChapterHadiths(
    volume: number,
    categoryId: string,
    chapterId: number,
  ): Promise<Hadith[]> {
    const allHadiths = await this.getVolumeHadiths(volume)
    return allHadiths.filter(
      (hadith) => hadith.categoryId === categoryId && hadith.chapterInCategoryId === chapterId,
    )
  },
}

export const uyunApi = {
  getUyunVolumes(): string[] {
    return ['Uyun-akhbar-al-Rida-Volume-1-Saduq', 'Uyun-akhbar-al-Rida-Volume-2-Saduq']
  },

  async getRandomUyunHadith(): Promise<Hadith> {
    return thaqalaynApi.getRandomHadithFromBook(getRandomFromList(this.getUyunVolumes()))
  },

  async getRandomHadithFromVolume(volume: number): Promise<Hadith> {
    if (volume < 1 || volume > 2) {
      throw new Error('Uyun akhbar al-Rida volume must be between 1 and 2')
    }
    return thaqalaynApi.getRandomHadithFromBook(`Uyun-akhbar-al-Rida-Volume-${volume}-Saduq`)
  },

  async searchUyun(query: string): Promise<QueryResponse> {
    const responses = await Promise.all(
      this.getUyunVolumes().map((id) => thaqalaynApi.searchBook(id, query)),
    )
    const results = responses.flatMap((response) => response.results)
    return { results, total: results.length }
  },

  async getVolumeHadiths(volume: number): Promise<Hadith[]> {
    if (volume < 1 || volume > 2) {
      throw new Error('Uyun akhbar al-Rida volume must be between 1 and 2')
    }
    return thaqalaynApi.getBookHadiths(`Uyun-akhbar-al-Rida-Volume-${volume}-Saduq`)
  },

  async getVolumeChapterStructure(volume: number): Promise<ChapterStructure> {
    const hadiths = await this.getVolumeHadiths(volume)
    return buildChapterStructure(hadiths)
  },

  async getChapterHadiths(
    volume: number,
    categoryId: string,
    chapterId: number,
  ): Promise<Hadith[]> {
    const allHadiths = await this.getVolumeHadiths(volume)
    return allHadiths.filter(
      (hadith) => hadith.categoryId === categoryId && hadith.chapterInCategoryId === chapterId,
    )
  },
}

export const bookApi = {
  async getBookHadiths(bookId: string): Promise<Hadith[]> {
    return thaqalaynApi.getBookHadiths(bookId)
  },

  async getBookChapterStructure(bookId: string): Promise<ChapterStructure> {
    const hadiths = await this.getBookHadiths(bookId)
    return buildChapterStructure(hadiths)
  },

  async getChapterHadiths(
    bookId: string,
    categoryId: string,
    chapterInCategoryId: number,
  ): Promise<Hadith[]> {
    const allHadiths = await this.getBookHadiths(bookId)
    return allHadiths.filter(
      (hadith) =>
        hadith.categoryId === categoryId && hadith.chapterInCategoryId === chapterInCategoryId,
    )
  },
}

function buildChapterStructure(hadiths: Hadith[]): ChapterStructure {
  const structure: ChapterStructure = {}

  for (const hadith of hadiths) {
    const categoryKey = hadith.category || 'Uncategorized'
    const chapterKey = hadith.chapter || 'No Chapter'

    structure[categoryKey] ??= {
      category: categoryKey,
      categoryId: hadith.categoryId || '',
      chapters: {},
    }

    structure[categoryKey].chapters[chapterKey] ??= {
      chapter: chapterKey,
      chapterInCategoryId: hadith.chapterInCategoryId || 0,
      hadiths: [],
    }

    structure[categoryKey].chapters[chapterKey].hadiths.push(hadith)
  }

  for (const category of Object.values(structure)) {
    category.chapters = Object.fromEntries(
      Object.entries(category.chapters).sort(
        ([, a], [, b]) => a.chapterInCategoryId - b.chapterInCategoryId,
      ),
    )
  }

  return structure
}
