import type { QueryResponse } from './api'
import { isArabicQuery } from './search-utils'
import { searchLocalHadiths } from './data/server-repository'

// Kept for compatibility with existing API routes/admin endpoints.
// Indexes are generated by scripts/data and loaded from local JSON shards.

export async function ensureArabicIndexReady(): Promise<void> {
  return
}

export function startArabicIndexRefresher(): void {
  return
}

export function stopArabicIndexRefresher(): void {
  return
}

export async function searchArabicLocally(
  query: string,
  bookIds?: string[],
): Promise<QueryResponse> {
  return searchLocalHadiths(query, bookIds)
}

export async function searchEnglishLocally(
  query: string,
  bookIds?: string[],
): Promise<QueryResponse> {
  return searchLocalHadiths(query, bookIds)
}

export function isArabic(text: string): boolean {
  return isArabicQuery(text)
}

export async function forceRebuild(): Promise<void> {
  return
}
