// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[bookSlug]" | "/[bookSlug]/chapter/[categoryId]/[chapterInCategoryId]" | "/[bookSlug]/hadith/[hadithId]" | "/al-kafi" | "/al-kafi/hadith/[hadithId]" | "/al-kafi/volume/[volumeId]/chapter/[categoryId]/[chapterInCategoryId]" | "/book/[bookId]" | "/book/[bookId]/chapter/[categoryId]/[chapterInCategoryId]" | "/bookmarks" | "/uyun-akhbar-al-rida/hadith/[hadithId]"
type AppRouteHandlerRoutes = "/api/admin/arabic-index-status" | "/api/admin/rebuild-arabic-index" | "/api/search"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[bookSlug]": { "bookSlug": string; }
  "/[bookSlug]/chapter/[categoryId]/[chapterInCategoryId]": { "bookSlug": string; "categoryId": string; "chapterInCategoryId": string; }
  "/[bookSlug]/hadith/[hadithId]": { "bookSlug": string; "hadithId": string; }
  "/al-kafi": {}
  "/al-kafi/hadith/[hadithId]": { "hadithId": string; }
  "/al-kafi/volume/[volumeId]/chapter/[categoryId]/[chapterInCategoryId]": { "volumeId": string; "categoryId": string; "chapterInCategoryId": string; }
  "/api/admin/arabic-index-status": {}
  "/api/admin/rebuild-arabic-index": {}
  "/api/search": {}
  "/book/[bookId]": { "bookId": string; }
  "/book/[bookId]/chapter/[categoryId]/[chapterInCategoryId]": { "bookId": string; "categoryId": string; "chapterInCategoryId": string; }
  "/bookmarks": {}
  "/uyun-akhbar-al-rida/hadith/[hadithId]": { "hadithId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
