// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from './routes.js'
import type { ResolvingMetadata, ResolvingViewport } from 'next/types.js'
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        props: { params: Promise<ParamMap[Route]> } & any,
      ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>,
      ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void
  POST?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void
  PUT?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void
  PATCH?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void
  DELETE?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void
  HEAD?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void
  OPTIONS?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void
}

// Validate ../../app/[bookSlug]/chapter/[categoryId]/[chapterInCategoryId]/page.tsx
{
  type __IsExpected<
    Specific extends AppPageConfig<'/[bookSlug]/chapter/[categoryId]/[chapterInCategoryId]'>,
  > = Specific
  const handler =
    {} as typeof import('../../app/[bookSlug]/chapter/[categoryId]/[chapterInCategoryId]/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[bookSlug]/hadith/[hadithId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/[bookSlug]/hadith/[hadithId]'>> = Specific
  const handler = {} as typeof import('../../app/[bookSlug]/hadith/[hadithId]/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[bookSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/[bookSlug]'>> = Specific
  const handler = {} as typeof import('../../app/[bookSlug]/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/al-kafi/hadith/[hadithId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/al-kafi/hadith/[hadithId]'>> = Specific
  const handler = {} as typeof import('../../app/al-kafi/hadith/[hadithId]/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/al-kafi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/al-kafi'>> = Specific
  const handler = {} as typeof import('../../app/al-kafi/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/al-kafi/volume/[volumeId]/chapter/[categoryId]/[chapterInCategoryId]/page.tsx
{
  type __IsExpected<
    Specific extends
      AppPageConfig<'/al-kafi/volume/[volumeId]/chapter/[categoryId]/[chapterInCategoryId]'>,
  > = Specific
  const handler =
    {} as typeof import('../../app/al-kafi/volume/[volumeId]/chapter/[categoryId]/[chapterInCategoryId]/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/book/[bookId]/chapter/[categoryId]/[chapterInCategoryId]/page.tsx
{
  type __IsExpected<
    Specific extends AppPageConfig<'/book/[bookId]/chapter/[categoryId]/[chapterInCategoryId]'>,
  > = Specific
  const handler =
    {} as typeof import('../../app/book/[bookId]/chapter/[categoryId]/[chapterInCategoryId]/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/book/[bookId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/book/[bookId]'>> = Specific
  const handler = {} as typeof import('../../app/book/[bookId]/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/bookmarks'>> = Specific
  const handler = {} as typeof import('../../app/bookmarks/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/'>> = Specific
  const handler = {} as typeof import('../../app/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/uyun-akhbar-al-rida/hadith/[hadithId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/uyun-akhbar-al-rida/hadith/[hadithId]'>> =
    Specific
  const handler = {} as typeof import('../../app/uyun-akhbar-al-rida/hadith/[hadithId]/page.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/arabic-index-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<'/api/admin/arabic-index-status'>> =
    Specific
  const handler = {} as typeof import('../../app/api/admin/arabic-index-status/route.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/rebuild-arabic-index/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<'/api/admin/rebuild-arabic-index'>> =
    Specific
  const handler = {} as typeof import('../../app/api/admin/rebuild-arabic-index/route.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<'/api/search'>> = Specific
  const handler = {} as typeof import('../../app/api/search/route.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<'/'>> = Specific
  const handler = {} as typeof import('../../app/layout.js')
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
