// Canonical IJMES-style transliterations for recurring narrator-name tokens.
// Names are reconstructed token-by-token so the same Arabic word is always
// rendered identically across the complete rijal dataset. Keep overrides here
// for words whose short vowels cannot be recovered from unvocalized Arabic;
// the deterministic fallback covers every rarer token without an external API.
const TOKEN_OVERRIDES = new Map(
  Object.entries({
    بن: 'b.',
    ابن: 'ibn',
    بنت: 'bt.',
    أبو: 'Abū',
    ابو: 'Abū',
    أبي: 'Abī',
    ابى: 'Abī',
    أم: 'Umm',
    ام: 'Umm',
    عبد: 'ʿAbd',
    عبيد: 'ʿUbayd',
    عبيدة: 'ʿUbaydah',
    الله: 'Allāh',
    الرحمان: 'Raḥmān',
    الرحمن: 'Raḥmān',
    الدين: 'Dīn',
    السلام: 'Salām',
    مولى: 'mawlā',
    والد: 'father of',
    والده: 'his father',
    أخو: 'brother of',
    جد: 'grandfather of',
    صاحب: 'companion of',
    بياع: 'seller of',
    آدم: 'Ādam',
    محمد: 'Muḥammad',
    محمود: 'Maḥmūd',
    أحمد: 'Aḥmad',
    احمد: 'Aḥmad',
    حمدان: 'Ḥamdān',
    حماد: 'Ḥammād',
    حميد: 'Ḥumayd',
    حسان: 'Ḥassān',
    حبيب: 'Ḥabīb',
    حارث: 'Ḥārith',
    حسن: 'Ḥasan',
    حسين: 'Ḥusayn',
    صبيح: 'Ṣubayḥ',
    علي: 'ʿAlī',
    عيسى: 'ʿĪsā',
    عمر: 'ʿUmar',
    عمرو: 'ʿAmr',
    عثمان: 'ʿUthmān',
    عمار: 'ʿAmmār',
    عامر: 'ʿĀmir',
    عمران: 'ʿImrān',
    عمير: 'ʿUmayr',
    عباس: 'ʿAbbās',
    العباس: 'al-ʿAbbās',
    عاصم: 'ʿĀṣim',
    عابد: 'ʿĀbid',
    عباد: 'ʿAbbād',
    عطاء: 'ʿAṭāʾ',
    علاء: 'ʿAlāʾ',
    عطية: 'ʿAṭiyyah',
    عتبة: 'ʿUtbah',
    عقبة: 'ʿUqbah',
    عوف: 'ʿAwf',
    عياض: 'ʿIyāḍ',
    عياش: 'ʿAyyāsh',
    عيينة: 'ʿUyaynah',
    مهدي: 'Mahdī',
    المهدي: 'al-Mahdī',
    إبراهيم: 'Ibrāhīm',
    ابراهيم: 'Ibrāhīm',
    إسماعيل: 'Ismāʿīl',
    اسماعيل: 'Ismāʿīl',
    إسحاق: 'Isḥāq',
    اسحاق: 'Isḥāq',
    إدريس: 'Idrīs',
    ادريس: 'Idrīs',
    أيوب: 'Ayyūb',
    ايوب: 'Ayyūb',
    أبان: 'Abān',
    ابان: 'Abān',
    أسباط: 'Asbāṭ',
    اسباط: 'Asbāṭ',
    أسد: 'Asad',
    اسد: 'Asad',
    أسلم: 'Aslam',
    اسلم: 'Aslam',
    أعين: 'Aʿyan',
    اعين: 'Aʿyan',
    أسعد: 'Asʿad',
    اسعد: 'Asʿad',
    جعفر: 'Jaʿfar',
    موسى: 'Mūsā',
    يحيى: 'Yaḥyā',
    يحيي: 'Yaḥyā',
    يونس: 'Yūnus',
    يوسف: 'Yūsuf',
    يعقوب: 'Yaʿqūb',
    يزيد: 'Yazīd',
    يسار: 'Yasār',
    يقطين: 'Yaqṭīn',
    سليمان: 'Sulaymān',
    سلمان: 'Salmān',
    سالم: 'Sālim',
    سلام: 'Salām',
    سليم: 'Sulaym',
    سلمة: 'Salamah',
    سعيد: 'Saʿīd',
    سعد: 'Saʿd',
    سفيان: 'Sufyān',
    سهل: 'Sahl',
    سويد: 'Suwayd',
    سيف: 'Sayf',
    سنان: 'Sinān',
    سراج: 'Sarrāj',
    سري: 'Sarī',
    شعيب: 'Shuʿayb',
    شريح: 'Shurayḥ',
    شهاب: 'Shihāb',
    هشام: 'Hishām',
    هاشم: 'Hāshim',
    هارون: 'Hārūn',
    هلال: 'Hilāl',
    هبة: 'Hibah',
    هيثم: 'Haytham',
    الهيثم: 'al-Haytham',
    زيد: 'Zayd',
    زياد: 'Ziyād',
    زكريا: 'Zakariyyā',
    زرارة: 'Zurārah',
    تغلب: 'Taghlib',
    خالد: 'Khālid',
    خليل: 'Khalīl',
    خزاز: 'Khazzāz',
    خلف: 'Khalaf',
    خلاد: 'Khallād',
    داود: 'Dāwūd',
    لؤلؤ: 'Luʾluʾ',
    اللؤلؤ: 'al-Luʾluʾ',
    لؤلؤي: 'Luʾluʾī',
    نوح: 'Nūḥ',
    صالح: 'Ṣāliḥ',
    صباح: 'Ṣabbāḥ',
    صدقة: 'Ṣadaqah',
    صيرفي: 'Ṣayrafī',
    صيقل: 'Ṣayqal',
    صادق: 'Ṣādiq',
    طلحة: 'Ṭalḥah',
    طاهر: 'Ṭāhir',
    طالب: 'Ṭālib',
    ثابت: 'Thābit',
    ثعلبة: 'Thaʿlabah',
    مثنى: 'Muthannā',
    فضيل: 'Fuḍayl',
    الفضل: 'al-Faḍl',
    فضل: 'Faḍl',
    قاسم: 'Qāsim',
    القاسم: 'al-Qāsim',
    قيس: 'Qays',
    قدامة: 'Qudāmah',
    كثير: 'Kathīr',
    مالك: 'Mālik',
    ملك: 'Malik',
    مروان: 'Marwān',
    مسلم: 'Muslim',
    مسعود: 'Masʿūd',
    منصور: 'Manṣūr',
    معاوية: 'Muʿāwiyah',
    معاذ: 'Muʿādh',
    معمر: 'Muʿammar',
    ميمون: 'Maymūn',
    مهران: 'Mihrān',
    نصر: 'Naṣr',
    نعيم: 'Nuʿaym',
    نعمان: 'Nuʿmān',
    النعمان: 'al-Nuʿmān',
    منذر: 'Mundhir',
    المنذر: 'al-Mundhir',
    وليد: 'Walīd',
    الوليد: 'al-Walīd',
    وهب: 'Wahb',
    بكر: 'Bakr',
    بكير: 'Bukayr',
    بشر: 'Bishr',
    بشير: 'Bashīr',
    بشار: 'Bashshār',
    بريد: 'Burayd',
    جابر: 'Jābir',
    جرير: 'Jarīr',
    جندب: 'Jundab',
    حفص: 'Ḥafṣ',
    حمزة: 'Ḥamzah',
    حنان: 'Ḥannān',
    حناط: 'Ḥannāṭ',
    حذاء: 'Ḥadhdhāʾ',
    حجاج: 'Ḥajjāj',
    حكيم: 'Ḥakīm',
    حكم: 'Ḥakam',
    الحكم: 'al-Ḥakam',
    رافع: 'Rāfiʿ',
    راشد: 'Rāshid',
    ربيعة: 'Rabīʿah',
    ربيع: 'Rabīʿ',
    الربيع: 'al-Rabīʿ',
    سفينة: 'Safīnah',
    صفوان: 'Ṣafwān',
    عطار: 'ʿAṭṭār',
    مفضل: 'Mufaḍḍal',
    المفضل: 'al-Mufaḍḍal',
    مغيرة: 'Mughīrah',
    المغيرة: 'al-Mughīrah',
    مختار: 'Mukhtār',
    المختار: 'al-Mukhtār',
    نضر: 'Naḍr',
    يسع: 'Yasaʿ',
    النضر: 'al-Naḍr',
    واحد: 'Wāḥid',
    الواحد: 'al-Wāḥid',
    كريم: 'Karīm',
    الكريم: 'al-Karīm',
    عزيز: 'ʿAzīz',
    العزيز: 'al-ʿAzīz',
    صمد: 'Ṣamad',
    الصمد: 'al-Ṣamad',
    أسود: 'Aswad',
    الاسود: 'al-Aswad',
    الأسود: 'al-Aswad',
    أحمر: 'Aḥmar',
    احمر: 'Aḥmar',
    أحمري: 'Aḥmarī',
    احمري: 'Aḥmarī',
    أزرق: 'Azraq',
    ازرق: 'Azraq',
    كوفي: 'Kūfī',
    قمي: 'Qummī',
    بصري: 'Baṣrī',
    بغدادي: 'Baghdādī',
    مدائني: 'Madāʾinī',
    رازي: 'Rāzī',
    واسطي: 'Wāsiṭī',
    نيسابوري: 'Naysābūrī',
    أشعري: 'Ashʿarī',
    اشعري: 'Ashʿarī',
    أسدي: 'Asadī',
    اسدي: 'Asadī',
    أزدي: 'Azdī',
    ازدي: 'Azdī',
    همداني: 'Hamadānī',
    أنصاري: 'Anṣārī',
    انصاري: 'Anṣārī',
    قرشي: 'Qurashī',
    هاشمي: 'Hāshimī',
    علوي: 'ʿAlawī',
    حسيني: 'Ḥusaynī',
    جعفي: 'Juʿfī',
    جعفري: 'Jaʿfarī',
    نخعي: 'Nakhaʿī',
    تميمي: 'Tamīmī',
    طائي: 'Ṭāʾī',
    عبدي: 'ʿAbdī',
    بجلي: 'Bajalī',
    كندي: 'Kindī',
    حضرمي: 'Ḥaḍramī',
    نهدي: 'Nahdī',
    نوفلي: 'Nawfalī',
    عجلي: 'ʿIjlī',
    نخاس: 'Nakhkhās',
    متوكل: 'Mutawakkil',
    قلنسي: 'Qalānisī',
    قلانسي: 'Qalānisī',
    غالب: 'Ghālib',
  }),
)

const LETTERS = {
  ء: 'ʾ',
  أ: 'ʾa',
  إ: 'ʾi',
  آ: 'ā',
  ا: 'ā',
  ب: 'b',
  ت: 't',
  ث: 'th',
  ج: 'j',
  ح: 'ḥ',
  خ: 'kh',
  د: 'd',
  ذ: 'dh',
  ر: 'r',
  ز: 'z',
  س: 's',
  ش: 'sh',
  ص: 'ṣ',
  ض: 'ḍ',
  ط: 'ṭ',
  ظ: 'ẓ',
  ع: 'ʿ',
  غ: 'gh',
  ف: 'f',
  ق: 'q',
  ك: 'k',
  ل: 'l',
  م: 'm',
  ن: 'n',
  ه: 'h',
  و: 'ū',
  ؤ: 'ʾ',
  ي: 'ī',
  ى: 'ā',
  ئ: 'ʾ',
  ة: 'ah',
  ک: 'k',
  ی: 'ī',
  پ: 'p',
  چ: 'ch',
  ژ: 'zh',
  گ: 'g',
}

const ARABIC_MARKS = /[\u0640\u064b-\u065f\u0670\u06d6-\u06ed]/gu

function cleanToken(token) {
  return token.normalize('NFC').replace(ARABIC_MARKS, '')
}

function capitalizeFirstLatin(value) {
  const lower = value.toLocaleLowerCase('en')
  return lower.replace(/\p{L}/u, (letter) => letter.toLocaleUpperCase('en'))
}

export function transliterateArabicToken(rawToken) {
  const token = cleanToken(rawToken)
  const override = TOKEN_OVERRIDES.get(token)
  if (override) return override

  // Reuse the same base-token spelling for the definite article and conjunction.
  if (token.startsWith('ال') && token.length > 2) {
    const base = transliterateArabicToken(token.slice(2))
    return `al-${capitalizeFirstLatin(base)}`
  }
  if (token.startsWith('و') && token.length > 2) {
    const remainder = token.slice(1)
    if (TOKEN_OVERRIDES.has(remainder) || remainder.startsWith('ال')) {
      return `wa-${transliterateArabicToken(remainder)}`
    }
  }

  const transliterated = Array.from(token, (letter) => LETTERS[letter] ?? letter).join('')
  return capitalizeFirstLatin(transliterated)
}

export function transliterateNarratorName(name) {
  return String(name || '')
    .replace(/[\p{Script=Arabic}\p{M}]+/gu, (token) => transliterateArabicToken(token))
    .replace(/\s+/g, ' ')
    .trim()
}

export function buildNarratorTransliterations(entries) {
  return Object.fromEntries(
    entries.map((entry) => [
      entry.id,
      {
        primary: transliterateNarratorName(entry.primaryName),
        aliases: Array.from(
          new Set((entry.aliases ?? []).map(transliterateNarratorName).filter(Boolean)),
        ),
      },
    ]),
  )
}

export function buildTokenTransliterationList(entries) {
  const tokens = new Set()
  for (const entry of entries) {
    for (const name of [entry.primaryName, ...(entry.aliases ?? [])]) {
      for (const match of String(name).matchAll(/[\p{Script=Arabic}\p{M}]+/gu)) {
        tokens.add(cleanToken(match[0]))
      }
    }
  }
  return Object.fromEntries(
    Array.from(tokens)
      .sort((a, b) => a.localeCompare(b, 'ar'))
      .map((token) => [token, transliterateArabicToken(token)]),
  )
}
